apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: facebooc-deploy
  namespace: facebooc
spec:
  sourceRef:
    kind: GitRepository
    name: facebooc-deploy
  path: ./flux
  interval: 1m
  targetNamespace: facebooc
  serviceAccountName: facebooc
  prune: false
