apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  sourceRef:
    kind: GitRepository
    name: instavote-deploy
  path: ./flux
  interval: 1m
  targetNamespace: instavote
  serviceAccountName: instavote
  prune: true
