apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/facebooc
patches:
  - target:
      kind: Kustomization
      name: facebooc-deploy
    patch: |-
      - op: replace
        path: /spec/path
        value: ./flux/staging
