apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: flagger-system
spec:
  url: https://kubernetes.github.io/ingress-nginx.git
  interval: 24h
