apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flagger-system
resources:
  - ../../base/flagger
  - ../../base/nginx-ingress
patches:
  - path: flagger_patch.yaml
    target:
      kind: Deployment
      name: flagger
  - path: nginx_ingress_patch.yaml
    target:
      kind: HelmRelease
      name: nginx-ingress
